language: python
python:
- '3.7'
sudo: required
install:
- pip install flask
script:
- python test.py
deploy:
  provider: heroku
  app: devopslabs4
  apy_key:
    secure: Pd1A37MH+NH/NuG9NG+ObJcLKUHwCAf1cdneLw6lIMJ9oewQpXuG8IkvEuhnkOgKP4CtqYYiyroBYuCx9WGh8dVnp/cr4TEyXK0cxY/lUiC6qPXnu5U/tqR7L/plGvqjBlpRWyravdrzNMMD4uVHmqb4Sa24OX3W6rEwx2++8v7PnXVc7ZDbJicKz1rRfOKKkcpXFos+6e7nwILsoBfoap3d9+3lIxpUxiIKA4T0OTHDBZZ67PEUXMzZ4BjGTqyqBHHHniMISZHl9Ph+DSgTYEP8Na1G8vAe0iq1rf1So19ALwwf0XQhepTZCfKPFjXWHZ8lszT7nglPZ7e4Xmkq1/j58eXbTvgicBm7zC1tqkmrTMetZlmEz2aByL5A2PcN9cdnXFKbbh1JzVXFqvrZYvqyAjYvmv8L0mjJV1lDg38d/fHH/s4jMIIOfWZwIycjiWbhTtAC6x4kqXmR3c1lD7S9SgTZEzBzTAaoiNsFtPaE/1TQxADDRy8oTaq3xv4qjOtcKWvazVcpXuxfXGq28ZHeFE4CrIbrJUQcNfHgwhyPq7dYC+MA732oO4748pfsJIVt87vDmMZAWANvethCBEG20Uy9kc4az5BPmmkz56jOAcVBP/UNDekkEk92NxJk68S9JOaBgkCPjnIk3LYmzRmXHN06qL0TZeo6zaLElT4=
