language: python
python:
- '3.7'
sudo: required
install:
- pip install flask
script:
- python test.py
deploy:
  provider: heroku
  app: devopslabs4
deploy4:
  apy_key:
    secure: qAp8+C837lflUaqxfDbRAmg/7ujwA0J/kHfztvqjBMFzVi4pIoB73TVLuC3cPSXaVOjHhzk+48S9POebuiYzWgeyojRzn68HkBWytt7YRGdQr9OUm/3wMezH0thpJvYjpCMgRBcY6J3KSwrsyoHksu2H6KaKQaddFUaTe2GvNZFV9IBoy+bokJsgM/5BDQJse34aCzSaMdSr03TBK0M5IGeY/ce+JObL7j22E7ZL8aL7EFmn/VYh0rOtvslXt8uU+H9wYvcgKB8wm77YnGMP6d1vlcqTyMgHhcChcsRxQ4p2Hdjph1wsASOAqnvHH8RDdD26PPW64NBJoS1ZMDNdsdBQtLprMfn3jwQhAfB8ChvySVMqbpdYvmSZNJxzXWPiWlQaNE0w57H+lgWIwuw4qbeKbP3qrO7+REWwi5t+dk9i4uXk1BG1NEj6i7FTfHfvKcxcVfnKxhuZb6qHGqJaQlhg4sYCeokHe0K+xR6SIoUy1NBRLdQZrwruJEdCZkB2O1GHve4NsVoiXAOd3bvBfIyh+nrrmoz//kF0u1/YJdAqjnw86m5eL3wGvEKYFKmqdMTJXIAhgy1JWAHrHYyxQ8uPA2nBvcWxDdyjqTupQDmgUSKlBvMVaiiIJnMQx2S1o5/zpHcuA4tcnKi6lUmBUb3ddmVLRQIQnxaDHKyZ4vQ=
